### PR TITLE
add demo html and todo compiled bundle

### PR DESCRIPTION
**Pull request by lapanoid**
This it PR on this issue - https://github.com/gaearon/redux-devtools/issues/19

### CODE REVIEW

**Comment by gaearon** [comment]
What is the build procedure? Can you add a package.json script which would switch to this branch, rebuild and push force?

**Comment by lapanoid** [comment]
Maybe this evening, had some work to do. 
To build you need to run this in root 
```
cd examples/todomvc && webpack --config webpack.config.js 
```
I don't know how to do switching to branch and push force.

**Comment by lapanoid** [comment]
Hah just standard git should work of coarse!

**Comment by gaearon** [comment]
Okay thanks. This helps me so far, I'll add an npm script myself.

**Comment by lapanoid** [comment]
@gaearon this should work

```
git checkout gh-pages && cd examples/todomvc && webpack --config webpack.config.js && cd ../../ && git add . && git commit -m \"rebuild todomvc bundle for demo\" && git push --force
```

**Pull request closed without merging**
