### PR TITLE
LogMonitor now attempts to call .toJS() on state entries.

### PR DESCRIPTION
**Pull request by davezuko**
This is an attempt to fix the unreadable state entries for ImmutableJS. I really didn't want to do the manipulation in the render method, but from what I saw in terms of how states are computed and stored I couldn't think of a better solution that didn't significantly alter that part of the codebase.

Anyways, feedback is appreciated. Maybe somebody has a better solution in mind, but this seems to be working for me.

### CODE REVIEW

**Comment by davezuko** [comment]
Aaaaand just saw https://github.com/gaearon/redux-devtools/pull/66 so this might not be the desired solution. I'll read through that again and see if I can rework the implementation.

**Comment by gaearon** [comment]
It's best if we can support anything iterable, not just Immutable.

**Comment by davezuko** [comment]
Right, totally makes sense. I'll try to update the PR later when I get home.

**Comment by gaearon** [comment]
Closing in favor of #79.

**Comment by gaearon** [comment]
Should be fixed in 1.1.0, please verify.

**Pull request closed without merging**
