### PR TITLE
add link to Deku monitor

### PR DESCRIPTION
**Pull request by nivanson**

### CODE REVIEW

**Comment by gaearon** [comment]
This seems like both a monitor + a Redux DevTools component re-implementation.
Maybe it's better to separate them?

**Comment by nivanson** [comment]
Yeah. I can separate them. I can do a pull request to redux-devtools with a deku-folder. Does that make sense or do you prefer if it is maintained outside of your repo?

I was going to re-implement the entire implementation of your default monitor too but it turned out to be quite a lot since JSONTree had to be re-implemented too.

**Comment by gaearon** [comment]
I'd rather prefer it in a separate repo, e.g. `redux-devtools-deku`.

**Comment by nivanson** [comment]
Ok, thanks for the feedback. Will separate. Closing PR. Maybe opening a new one when done. :+1:

**Pull request closed without merging**
