### PR TITLE
Fixed bug in sweep

### PR DESCRIPTION
**Pull request by taylorhakes**
Sweep was throwing an error because of an index out of range issue.

### CODE REVIEW

**Comment by gaearon** [comment]
Interesting why it happened. By that moment the actions are already filtered so shouldn't it point to the last state?

**Comment by taylorhakes** [comment]
I am a little confused at what you are asking. The `currentStateIndex` before this action occurs is normally pointing to the last element (before filter). The elements are then filtered, removing the ones that are skipped which makes the array shorter (smaller length). If you do `Math.max` it keeps the `currentStateIndex` the same, outside the bounds of the array. `Math.min` is needed to make sure the `currentStateIndex` is inside the bounds of the new array.

**Comment by gaearon** [comment]
Lol I'm bad at math. Thank you for explaining.

**Comment by gaearon** [comment]
Should be released in 0.1.3.

**Pull request merged**
