### PR TITLE
Show error message, not just a stack trace

### PR DESCRIPTION
**Pull request by sapegin**
Before:

After:

### CODE REVIEW

**Comment by zalmoxisus** [comment]
I don't think duplicating errors is a good way to fix it. Better to just replace console.error(err.stack || err)` with `console.error(err)`, so we'll get the message along with the stack.

I guess `err.stack` was added to fix the problem with Chrome, and since it is now fixed there by rethrowing the error, we don't need it anymore.

**Comment by zalmoxisus** [comment]
With `console.error(err.stack)` we get
screen shot 2016-02-04 at 5 10 02 pm
With `console.error(err)`
screen shot 2016-02-04 at 5 09 50 pm

**Comment by sapegin** [comment]
Cool, I’ve updated the PR.

**Comment by gaearon** [comment]
Can you please check before/after in Chrome, Firefox, and Safari?

**Comment by zalmoxisus** [comment]
I've tested as well in Safari. It doesn't affect Chrome. But we also have to change tests as we get the error object not a string now.

So,
```js
expect(spy.calls[0].arguments[0]).toMatch(
      /ReferenceError/
    );
```
should become
```js
expect(spy.calls[0].arguments[0].toString()).toMatch(
      /ReferenceError/
    );
```

**Comment by gaearon** [comment]
:+1:

**Comment by sapegin** [comment]
Tests are fixed.

**Comment by sapegin** [comment]
@zalmoxisus @gaearon What can I do to make this merged?

**Comment by gaearon** [comment]
Thanks for reminding. I will push out a patch later today.

**Comment by gaearon** [comment]
Out in 3.1.1.

**Pull request merged**
