### PR TITLE
Add demo

### PR DESCRIPTION
**Pull request by lapanoid**
Here you go. This is PR on this https://github.com/gaearon/redux-devtools/issues/19

### CODE REVIEW

**Comment by lapanoid** [comment]
Ouch there is also another branch.. wait for it..

**Comment by lapanoid** [comment]
https://github.com/gaearon/redux-devtools/pull/21

**Comment by lapanoid** [comment]
Had time and finally finished it, I am not a good bash scripter but I have tested it and it looks fine for me.

**Comment by lapanoid** [comment]
@gaearon do you need some other fixes or this is ok?

**Comment by gaearon** [comment]
Sorry, I got a bit confused. Should #20 and #21 both be merged? In what order?

**Comment by lapanoid** [comment]
https://github.com/gaearon/redux-devtools/pull/21 - just builded demo in gh-pages branch
https://github.com/gaearon/redux-devtools/pull/20 - master branch with script and link in readme
I guess order does not matter here cause it is different branches.

**Comment by gaearon** [comment]
Ah! It makes sense now. :-)

**Pull request closed without merging**
