### PR TITLE
Add support for Map nodes

### PR DESCRIPTION
**Pull request by bnoon**
I use Map() in my state for ordered lists and would like to inspect them.

### CODE REVIEW

**Comment by FredyC** [comment]
I think that this should be sorted out in a more generic way, since there is a lack of support for Immutable (see #51). The Map has method `toJSON` same as the ImmutableJS objects. If we use duck typing for such method, we don't need additional node type in my opinion.

**Comment by bnoon** [comment]
I agree that the copy/paste was a quick hack and the common functionality should be pulled out.

However, Map is a built-in object and sufficiently different from Object or Array to be special cased.

**Comment by FredyC** [comment]
Yeah, I guess that Map is different, but it's pretty much same as Map from Immutable. There is problem that you can have basically anything in your key, so it cannot be displayed easily in a tree view. Map can be more likely seen as a list of entries with keys and values.

**Comment by gaearon** [comment]
Can we somehow use iterators + `entries()` method to have a generic way to enumerate stuff?

**Comment by FredyC** [comment]
@gaearon Yeah, I think that might be a good way. The result is in both cases identical (https://jsbin.com/pirura/edit?js,console). And actually `entries()` is default iterator. It might be enough to check if there is an iterator present `obj[Symbol.iterator]`.

**Comment by bnoon** [comment]
I am closing this in favor of #79.  Thanks @FredyC!

**Comment by gaearon** [comment]
Should be fixed in 1.1.0, please verify.

**Pull request closed without merging**
