### PR TITLE
Solve the issue with loosing sourceMaps in Chrome

### LINKED ISSUE #193: Source maps not working
Hi there,

I use [este dev stack](https://github.com/este/este) and when I appended a redux-devtools, then source maps stopped working - when some error occure it does not show the exact file where it occures...

### PR DESCRIPTION
**Pull request by zalmoxisus**
Fix #193. Related to #194.

### CODE REVIEW

**Comment by gaearon** [comment]
Is there any benefit to hardcoding a chrome check here? I'd rather have a single way of doing thing as long as this method doesn't bring any downsides in other browsers.

**Comment by zalmoxisus** [comment]
Yes, unfortunately, I figured that it has downsides in Firefox. When clicking to the error line in the console, Firefox cannot open the file from sourceMaps. Though it works well with `console.error(stack)`.
As about Safari, it shows only the error tree without any lines in both cases.

**Comment by gaearon** [comment]
Got it, thanks.

**Comment by gaearon** [comment]
Out in 3.0.1.

**Pull request merged**
