### PR TITLE
Upgrade lodash dependency to ^4.2.0.

### PR DESCRIPTION
**Pull request by shouze**

### CODE REVIEW

**Comment by gaearon** [comment]
I don't think this is how Lodash 4 functions are named. They each have their own file in top level directory.

**Comment by shouze** [comment]
Ok I Will fix that... So why closing this PR?

**Comment by gaearon** [comment]
Ah, if you’re happy to update now, please feel free to!

**Comment by gaearon** [comment]
I’m just in the middle of merging other PRs so I can as well do that manually if you don’t have time right now. Please let me know!

**Comment by gaearon** [comment]
I merged your PR and fixed the imports. Thanks for contributing! I even forgot we use Lodash here :smile:

**Pull request merged**
