### PR TITLE
v0.14 compatiblity import ReactDOM, { findDOMNode } from "react-dom

### PR DESCRIPTION
**Pull request by eyala-stratoscale**

### CODE REVIEW

**Comment by gaearon** [comment]
This is probably the fifth PR doing this. :stuck_out_tongue: 

I'll release 0.14-compliant updates of **all Redux related packages together.**
This week. ;-)

**Comment by eyala-stratoscale** [comment]
Sorry about that.
It was bugging me, I updated my app to v0.14 and still had this warning that kept coming up.
Thank You

**Comment by gaearon** [comment]
Yeah I know. We'll fix it soon. It's just a warning so for now please ignore it.

**Comment by gaearon** [comment]
You can track it here https://github.com/gaearon/redux-devtools/issues/152

**Comment by gaearon** [comment]
Please try 3.0 Beta 2 and leave feedback.
It includes React 0.14 support: https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2

**Pull request closed without merging**
