### PR TITLE
lightweight css animations for new actions entering the log.

### PR DESCRIPTION
**Pull request by threepointone**
while we ponder react-motion in #52, consider a simpler alternative for now :) this PR adds a css fadeIn animation to entries in the actions log.

### CODE REVIEW

**Comment by nicinabox** [comment]
Would be awesome if you could show a gif of it!

**Comment by threepointone** [comment]
it's quite subtle, doesn't show well (and seems longer) in this gif http://recordit.co/ss6t7FyU7H :|

**Comment by nicinabox** [comment]
Nice! What happens when you get down to the bottom and it starts scrolling?

**Comment by threepointone** [comment]
just adds it at the bottom as it already does now, along with the subtle fade. try it, it's really not much :)

**Comment by gaearon** [comment]
I'll defer any visual decisions to @nicinabox to approve

**Comment by nicinabox** [comment]
How do we feel about the flash? For reference:

fade mov

**Comment by gaearon** [comment]
What if we the opposite? Start off actions brighter than usual, then let them “cool down”. Like changing nodes in Chrome inspector.

**Comment by nicinabox** [comment]
That's a neat effect too. I think the biggest thing that's lacking with each of these is you don't really see the content move upwards (but these are still an improvement).

flash mov

**Comment by dzannotti** [comment]
i like all 3

**Comment by nicinabox** [comment]
Oops, probably wasn't clear on the first one. It's @threepointone's. I just recorded at 30fps and showed scrolling.

**Comment by nicinabox** [comment]
Could we append it *then* animate scrolling to the bottom?

**Comment by gaearon** [comment]
Yeah. Let's replace naïve scrolling with something like https://github.com/alexkuz/additive-animation#usage-example?

**Comment by gaearon** [comment]
Closing, as I don't currently have time to make it better, and scrolling seems to be important for the desired effect. If someone would like to implement it, please do it in https://github.com/gaearon/redux-devtools-log-monitor instead (track https://github.com/gaearon/redux-devtools/pull/132 for discussion).

**Pull request closed without merging**
