### PR TITLE
Use react-dom for 0.14.0 compability.

### PR DESCRIPTION
**Pull request by ronag**
Fixes React 0.14 warning.

### CODE REVIEW

**Comment by ooflorent** [comment]
#114 seems better to me

**Comment by gaearon** [comment]
This is fixed in https://github.com/gaearon/redux-devtools-log-monitor that is being split away from the main repo. I don't intend to merge this here, so closing. See https://github.com/gaearon/redux-devtools/pull/132 to track the split.

**Comment by gaearon** [comment]
You can track it here: https://github.com/gaearon/redux-devtools/issues/152

**Comment by gaearon** [comment]
Please try 3.0 Beta 2 and leave feedback.
It includes React 0.14 support: https://github.com/gaearon/redux-devtools/releases/tag/v3.0.0-beta-2

**Pull request closed without merging**
