### PR TITLE
Update to Babel 6

### PR DESCRIPTION
**Pull request by colinmeinke**
I have split out `export default` onto new lines [because of this babel bug with static](https://phabricator.babeljs.io/T2779).

### CODE REVIEW

**Comment by gaearon** [comment]
Can you please change this:

* `export default` bug seems fixed—no workaround needed, I think?
* Please use `es2015-loose` + `stage-0` + `react` presets

**Comment by colinmeinke** [comment]
Sure, can do this tomorrow.

**Comment by gaearon** [comment]
Thanks!

**Comment by ewendel** [comment]
Do you have any further comments, @gaearon ? Would be awesome to get a fix for this warning out sometime soon :-)

**Comment by gaearon** [comment]
What warning?

**Comment by ewendel** [comment]
This one, caused by `LogMonitor` using the deprecated function call:

`Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.`

**Comment by zalmoxisus** [comment]
@ewendel, probably you didn't update `redux-devtools-log-monitor`. I don't see any warnings.

**Comment by gaearon** [comment]
@ewendel This pull request is about updating Babel version used internally. It's not related to React or its warnings. That said, this React warning is definitely gone with Redux DevTools 3.0. Please check your versions carefully.

**Comment by ewendel** [comment]
I followed a hashtag-trail here about that warning, but it turns out our internal npm registry was causing some versioning issues, giving us and old log monitor - sorry about that!

**Comment by gaearon** [comment]
Thanks again.

**Comment by colinmeinke** [comment]
No problem. Thank you for all your work :smiley:

**Pull request merged**
