### PR TITLE
Added React v16 peer dependency support

### PR DESCRIPTION
**Pull request by jayfunk**
After upgrading to React 16 the redux devtools throws a peerDependency warning.

`npm WARN redux-devtools@3.4.0 requires a peer of react@^0.14.9 || ^15.3.0 but none was installed.`

This fix it to stop this warning and allow downstream modules to build without peerDependency failures.

Linking to #381

### CODE REVIEW

**Comment by mxl** [comment]
What does prevent us from merging this PR?

**Comment by springuper** [comment]
We should merge it asap if all tests pass.

**Comment by ezmiller** [comment]
Great that this is done. When will it be installable via npm? Looks like v3.4.0 doesn't have these commits?

**Comment by mac-s-g** [comment]
@ezmiller 3.4.1 is published.  and i can verify that it fixes the issue.

**Pull request merged**
